### ISSUE TITLE
device encryption: untested

### ISSUE THREAD

**Issue by steadfasterX** [Suicide-Squirrel/issues_pie#12]
atm device encryption is fully untested and so can result in total loss of data when enabling.

**Comment by steadfasterX** [comment]
tested in lineage-16.0-20190620-UNOFFICIAL-h815.zip successfully.

**Comment by fmikker** [comment]
Hi,
I just tried to enable device encryption on my G4 with Magisk installed and enabled, and the device seems to be stuck in a reboot loop where the device starts up and shows the LG logo, and then suddenly restarts again. Some times it comes as far as the lineage boot "line" shows up, but then reboots again.
This has been going on for about 20 minutes now with countless reboots happeing every 5-8 seconds.

Release: lineage-16.0-20201024-UNOFFICIAL-h815.zip
Twrp version: me.twrp.twrpapp-26.apk
Magisk: Magisk-v21.1.zip
No google play service installed whatsoever.
