### ISSUE TITLE
Bluetooth address loader may fail in some situations

### ISSUE THREAD

**Issue by steadfasterX** [Suicide-Squirrel/issues_pie#14]
BT address gets read from.MISC which is denied by neverallow and so needs proper handling

> 05-13 17:52:02.983 9828 9870 D : get_local_address: Trying /data/misc/bluetooth/bdaddr 05-13 17:52:02.983 9828 9870 E : get_local_address: Got Invalid BDA '00:00:00:00:00:00' from /data/misc/bluetooth/bdaddr 05-13 17:52:02.983 9828 9870 F android.hardware.bluetooth@1.0-impl: Open: No Bluetooth Address!

`01-01 03:42:18.407 582 582 I auditd : type=1400 audit(0.0:35): avc: denied { read } for comm="bdaddr_loader" name="mmcblk0p22" dev="tmpfs" ino=251 scontext=u:r:bdaddr_loader:s0 tcontext=u:object_r:block_device:s0 tclass=blk_file permissive=1 
01-01 03:42:18.407 582 582 I auditd : type=1400 audit(0.0:36): avc: denied { open } for comm="bdaddr_loader" path="/dev/block/mmcblk0p22" dev="tmpfs" ino=251 scontext=u:r:bdaddr_loader:s0 tcontext=u:object_r:block_device:s0 tclass=blk_file permissive=1`

**Comment by tommyboylab** [comment]
Created separate ticket pertaining to the below issue: #17

**Comment by steadfasterX** [comment]
> @steadfasterX I've been finding this issue is occurring for me quite often. Any time my music is paused (or the song list ends) the Bluetooth disconnects / Reconnects itself. Here's the Logcat of the issue I'm experiencing.
> 
> [logcat.txt](https://github.com/Suicide-Squirrel/issues_pie/files/3220188/logcat.txt)


Do you loose your bt address when that happens? Otherwise this is another issue and you should open a new issue. Also provide on which exact build you test.

Edit 
Just checked your logcat and you do not seem to loose your bt address .  So open a  new issue as this is not related .
