### ISSUE TITLE
Bluetooth disconnects upon finishing audio playback

### ISSUE THREAD

**Issue by tommyboylab** [Suicide-Squirrel/issues_pie#17]
### While listening to media through a Bluetooth connection, anytime the audio controller is placed in standby the Bluetooth device disconnects

**Ex: Songs played after one another will continue to do so with no problem. Whenever the Songlist finishes, album finishes, Bluetooth disconnects.**

**Sometimes Bluetooth will connect again automatically, other times Bluetooth  Settings must be open for the device to reconnect**

Happened on the latest Lineage (20190525) and AEX (20190524) -- Logcat from AEX

LG G4 H812 USU 
- Flashed Bootloader from http://leech.binbash.it:8008/stock/LG/h812/20z/
- Flashed Modem from https://androidfilehost.com/?w=files&flid=239970

[logcat.txt](https://github.com/Suicide-Squirrel/issues_pie/files/3220555/logcat.txt)

**Comment by steadfasterX** [comment]
cannot be re-produced in latest pie build from today (not yet released though)
re-open (with logs stating **at which time** the disconnect happen) if that issue persists on builds after today.
