### ISSUE TITLE
pixel launcher crashing-LOS 16 

### ISSUE THREAD

**Issue by horvalos** [Suicide-Squirrel/issues_pie#19]
Pixel launcher keeps crashing
log provided
https://paste.omnirom.org/view/4b47d9b7
[pixel-launcher-log.txt](https://github.com/Suicide-Squirrel/issues_pie/files/3254234/pixel-launcher-log.txt)

**Comment by steadfasterX** [comment]
the issue is:

> --------- beginning of crash
> 07-03 00:35:08.240 15774 15774 E AndroidRuntime: FATAL EXCEPTION: main
> 07-03 00:35:08.240 15774 15774 E AndroidRuntime: Process: com.google.android.apps.nexuslauncher, PID: 15774
> 07-03 00:35:08.240 15774 15774 E AndroidRuntime: java.lang.NoSuchMethodError: No static method setContextPriority(I)V in class Landroid/view/ThreadedRenderer; or its super classes (declaration of 'android.view.ThreadedRenderer' appears in /system/framework/framework.jar!classes2.dex)
> 07-03 00:35:08.240 15774 15774 E AndroidRuntime:        at com.android.systemui.shared.system.ThreadedRendererCompat.setContextPriority(SourceFile:31)
> 07-03 00:35:08.240 15774 15774 E AndroidRuntime:        at com.android.quickstep.QuickstepProcessInitializer.init(SourceFile:33)
> 07-03 00:35:08.240 15774 15774 E AndroidRuntime:        at com.google.android.apps.nexuslauncher.NexusProcessInitializer.init(SourceFile:20)
> 07-03 00:35:08.240 15774 15774 E AndroidRuntime:        at com.android.launcher3.MainProcessInitializer.initialize(SourceFile:32)
> 07-03 00:35:08.240 15774 15774 E AndroidRuntime:        at com.android.launcher3.LauncherProvider.onCreate(SourceFile:117)
> 07-03 00:35:08.240 15774 15774 E AndroidRuntime:        at android.content.ContentProvider.attachInfo(ContentProvider.java:1920)
> 07-03 00:35:08.240 15774 15774 E AndroidRuntime:        at android.content.ContentProvider.attachInfo(ContentProvider.java:1895)
> 07-03 00:35:08.240 15774 15774 E AndroidRuntime:        at android.app.ActivityThread.installProvider(ActivityThread.java:6440)
> 07-03 00:35:08.240 15774 15774 E AndroidRuntime:        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5987)
> 07-03 00:35:08.240 15774 15774 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5902)
> 07-03 00:35:08.240 15774 15774 E AndroidRuntime:        at android.app.ActivityThread.access$1100(ActivityThread.java:200)
> 07-03 00:35:08.240 15774 15774 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
> 07-03 00:35:08.240 15774 15774 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
> 07-03 00:35:08.240 15774 15774 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
> 07-03 00:35:08.240 15774 15774 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6718)
> 07-03 00:35:08.240 15774 15774 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
> 07-03 00:35:08.240 15774 15774 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> 07-03 00:35:08.240 15774 15774 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
> 07-03 00:35:08.246  1021  5182 W ActivityManager:   Force finishing activity com.google.android.apps.nexuslauncher/.NexusLauncherActivity
> 07-03 00:35:08.252  1021  5182 W ActivityManager:   Force finishing activity com.android.launcher3/.lineage.LineageLauncher

but setContextPriority is there:

https://github.com/LineageOS/android_frameworks_base/blob/lineage-16.0/core/java/android/view/ThreadedRenderer.java#L1172-L1180

sorry can't fix google issues here..

**Comment by josephcsible** [comment]
I had this problem myself. I discovered that you can work around it by installing Pixel Launcher (I used the apk from OpenGApps) as a system app (in /system/priv-app).
