### ISSUE TITLE
Headset microphone doesn't work

### ISSUE THREAD

**Issue by marktiu** [Suicide-Squirrel/issues_pie#22]
Microphone doesn't work on headset.

Calling a person with a corded mic/headset, the person can't hear me.

Unplugged it and talked directly on phone works ok.

Just flashed recently from 15 and worked ok there.  Flashed because of the Bluetooth issue.

**Comment by steadfasterX** [comment]
No log  no fix 

http://bit.do/logcat

**Comment by marktiu** [comment]
Sorry noob on this :)

Ill do a bit more testing and if it doesn't work I'll post the log

**Comment by steadfasterX** [comment]
Closed because..?

**Comment by marktiu** [comment]
Seems to be headset issue.  Tried with a few and it worked, weird coincidence that it stopped working when I upgraded, so false alarm
