### ISSUE TITLE
h815, h815 UsU, H811 - build 2019-07-10 only: google play on clean install fails

### ISSUE THREAD

**Issue by steadfasterX** [Suicide-Squirrel/issues_pie#23]
When you install openGapps and starting Google Play the first time you might see an error like 

_"Error communicating with Google servers, please try again later"._

without a way to login or going on or (when coming from a full clean flash) you might not be abe to complete the google first boot wizard.

This issue is due to the fact we enforcing now and .. I missed a little policy here. :p 

This affects the mentioned models only as those were build already before I fixed that.

But the following is a workaround until I can re-build for those:

### Option 1: after a factory reset / full clean flash

1. install LOS - do NOT install opengapps
1. boot LOS and finish the wizard
1. reboot to TWRP
1. flash opengapps & boot to LOS
1. follow the next topic "after a regular clean flash"

### Option 2: after a regular clean flash

1. enable "[Developer Options](http://bfy.tw/OVom)" and open it
1. Set "Root Access" -> "ADB only"
1. Enable USB debugging & connect your PC
1. you will get prompted to allow your PC (confirm that)
1. in Settings -> Apps : disable "google play store" and "force stop" it
2. in storage: clear storage and cache
3. (no reboot)
4. execute: `adb root`
4. execute: `adb shell "setenforce permissive"`
1. in Settings -> Apps : enable "google play store"
5. start play store & login (that should work now)

The above is needed only once when logging in the first time. You can now safely reboot and being enforced again while play store will work as before.

**Comment by steadfasterX** [comment]
fixed by: 
https://github.com/Suicide-Squirrel/android_device_lge_g4-common/commit/fa10f2d0f5ef5222d8c1b44296cddeef3d7c21b0
https://github.com/Suicide-Squirrel/android_device_lge_g4-common/commit/19f780593a3866986b23ae4609c1b25306f51fcf

issue will be closed, the above 3 models will get a new build once the current jenkins run has finished.

**Comment by ogunbaysal** [comment]
i did the fixes you said above for this error. But now, when i want to update open-gapps on google play, phone make soft-reboot for each of apps. Can you add this solution to a new update.

**Comment by steadfasterX** [comment]
> i did the fixes you said above for this error. But now, when i want to update open-gapps on google play, phone make soft-reboot for each of apps. Can you add this solution to a new update.

if you provide the logs..

https://forum.xda-developers.com/showpost.php?p=79882096&postcount=378
