### ISSUE TITLE
I can't change/update my ROM

### ISSUE THREAD

**Issue by androeat** [Suicide-Squirrel/issues_pie#25]
I was using 2019.05.15 dated version of LOS. I tried change my ROM with AEX. It didn't. After I tried update LOS. I got same things in both. Installation is finishing perfectly. In booting, screen being completely blue and stuck there. It was full clean installation and I installed modem.

I am trying 2019.05.15 and it is working perfectly. (with known issues)

Before all I used AEX. I am using H815TR UsU'd.

**Comment by steadfasterX** [comment]
blue screen means outdated bootloader stack. Always share a pic/photo of such an error.
upgrade to 20p as described in the UsU FAQ #20b) --> https://forum.xda-developers.com/showpost.php?p=75817533&postcount=2
