### ISSUE TITLE
button: "Long press for torch" does not work

### ISSUE THREAD

**Issue by steadfasterX** [Suicide-Squirrel/issues_pie#26]
yep. true. that option is unusable and even more : if you enable it it will cause crashes in the camera daemon. 

**so KEEP THAT OPTION DISABLED.**

![photo_2019-07-24_15-48-28](https://user-images.githubusercontent.com/8750713/61799032-a31da800-ae2a-11e9-9060-143a8aed068b.jpg)

related to: #8 (if that workaround can be removed the option will be usable again)

log crash example :

> 07-24 08:51:28.431     0     0 E [    9.358246 / 07-24 12:51:28.425][1] qpnp_flash_led_brightness_set: 1305: name = led:flash_0, val = 0
> 07-24 08:51:28.431     0     0 E [    9.358298 / 07-24 12:51:28.425][1] qpnp_flash_led_brightness_set: 1305: name = led:flash_1, val = 0
> 07-24 08:51:28.431     0     0 E [    9.358310 / 07-24 12:51:28.425][1] qpnp_flash_led_brightness_set: 1305: name = led:torch_0, val = 0
> 07-24 08:51:28.431     0     0 E [    9.358321 / 07-24 12:51:28.425][1] qpnp_flash_led_brightness_set: 1305: name = led:torch_1, val = 0
> 07-24 08:51:28.431     0     0 E [    9.358410 / 07-24 12:51:28.425][1] BUG: scheduling while atomic: mm-qcamera-daem/1027/0x00000002
> 07-24 08:51:28.431     0     0 W         : [    9.358418 / 07-24 12:51:28.425][1] Modules linked in:
> 07-24 08:51:28.431     0     0 W [    9.358431 / 07-24 12:51:28.425][1] CPU: 1 PID: 1027 Comm: mm-qcamera-daem Tainted: G        W    3.10.108-g4750871 #1
> 07-24 08:51:28.431     0     0 W         : [    9.358440 / 07-24 12:51:28.425][1] Hardware name: Qualcomm Technologies, Inc. MSM8992 P1 GLOBAL COM (DT)
> 07-24 08:51:28.431     0     0 W         : [    9.358449 / 07-24 12:51:28.425][1] Call trace:
> 07-24 08:51:28.431     0     0 W         : [    9.358470 / 07-24 12:51:28.425][1] [<ffffffc000087854>] dump_backtrace+0x0/0x244
> 07-24 08:51:28.431     0     0 W         : [    9.358482 / 07-24 12:51:28.425][1] [<ffffffc000087aa8>] show_stack+0x10/0x1c
> 07-24 08:51:28.431     0     0 W         : [    9.358499 / 07-24 12:51:28.425][1] [<ffffffc000c77750>] dump_stack+0x1c/0x28
> 07-24 08:51:28.431     0     0 W         : [    9.358513 / 07-24 12:51:28.425][1] [<ffffffc0000ca0d8>] __schedule_bug+0x40/0x58
> 07-24 08:51:28.431     0     0 W         : [    9.358525 / 07-24 12:51:28.425][1] [<ffffffc000c800c0>] __schedule+0x94/0x7a0
> 07-24 08:51:28.431     0     0 W         : [    9.358535 / 07-24 12:51:28.425][1] [<ffffffc000c80820>] schedule+0x54/0x60
> 07-24 08:51:28.431     0     0 W         : [    9.358545 / 07-24 12:51:28.425][1] [<ffffffc000c80b80>] schedule_preempt_disabled+0x10/0x24
> 07-24 08:51:28.431     0     0 W         : [    9.358556 / 07-24 12:51:28.425][1] [<ffffffc000c7f3ec>] __mutex_lock_slowpath+0x180/0x1f4
> 07-24 08:51:28.431     0     0 W         : [    9.358565 / 07-24 12:51:28.425][1] [<ffffffc000c7f488>] mutex_lock+0x28/0x48
> 07-24 08:51:28.431     0     0 W         : [    9.358578 / 07-24 12:51:28.425][1] [<ffffffc0008e724c>] qpnp_flash_led_brightness_set+0x1c8/0x1f4
> 07-24 08:51:28.431     0     0 W         : [    9.358589 / 07-24 12:51:28.425][1] [<ffffffc0008e03a8>] led_set_brightness+0x54/0x60
> 07-24 08:51:28.431     0     0 W         : [    9.358599 / 07-24 12:51:28.425][1] [<ffffffc0008e0f70>] led_trigger_event+0x3c/0x60
> 07-24 08:51:28.431     0     0 W         : [    9.358613 / 07-24 12:51:28.425][1] [<ffffffc0007dac64>] msm_flash_off+0x94/0xf0
> 07-24 08:51:28.431     0     0 W         : [    9.358624 / 07-24 12:51:28.425][1] [<ffffffc0007da870>] msm_flash_init+0x1cc/0x24c
> 07-24 08:51:28.431     0     0 W         : [    9.358633 / 07-24 12:51:28.425][1] [<ffffffc0007daf94>] msm_flash_config+0x17c/0x208
> 07-24 08:51:28.431     0     0 W         : [    9.358643 / 07-24 12:51:28.425][1] [<ffffffc0007db1d8>] msm_flash_subdev_ioctl+0x1b8/0x214
> 07-24 08:51:28.431     0     0 W         : [    9.358652 / 07-24 12:51:28.425][1] [<ffffffc0007db444>] msm_flash_subdev_do_ioctl+0x210/0x278
> 07-24 08:51:28.431     0     0 W         : [    9.358667 / 07-24 12:51:28.425][1] [<ffffffc0007705e8>] video_usercopy+0x244/0x3dc
> 07-24 08:51:28.431     0     0 W         : [    9.358678 / 07-24 12:51:28.425][1] [<ffffffc0007dae0c>] msm_flash_subdev_fops_ioctl+0x10/0x1c
> 07-24 08:51:28.431     0     0 W         : [    9.358691 / 07-24 12:51:28.425][1] [<ffffffc00077ab64>] v4l2_compat_ioctl32+0x634/0x64c
> 07-24 08:51:28.431     0     0 W         : [    9.358709 / 07-24 12:51:28.425][1] [<ffffffc0001bb828>] compat_sys_ioctl+0x10c/0x1228

**Comment by gioyann** [comment]
Will be fixed? I find the "long press for torch" very very usefull!

**Comment by steadfasterX** [comment]
> Will be fixed? I find the "long press for torch" very very usefull!

it was closed with "wontfix" so no. it is due to the fact of how the camera has been implemented:
u can have a bad quality cam and longpress for torch fixed or (like it is implemented) with using LG blobs and good quality and no press for torch functionality.
