### ISSUE TITLE
H810 - screen lock issue

### ISSUE THREAD

**Issue by f-yang** [Suicide-Squirrel/issues_pie#28]
My device is H810, the screen lock is Swipe and cannot change to any others... I did full clean flash and install.. any ideas?

**Comment by steadfasterX** [comment]
https://forum.xda-developers.com/showpost.php?p=79998236&postcount=616

**Comment by steadfasterX** [comment]
As stated a log is required. I close it for now . Feel free to reopen with the requested logs.
