### ISSUE TITLE
3rd party apps - Google Maps not showing

### ISSUE THREAD

**Issue by pavlaras** [Suicide-Squirrel/issues_pie#29]
08-29 18:16:19.783 15119 16402 E GoogleApiHelper: unable to connect to reverse geocode service 
08-29 18:16:19.783 15119 16402 E GoogleApiHelper: java.io.IOException: Service not Available
08-29 18:16:19.783 15119 16402 E GoogleApiHelper: 	at android.location.Geocoder.getFromLocation(Geocoder.java:136)
08-29 18:16:19.783 15119 16402 E GoogleApiHelper: 	at com.life360.android.core.network.GoogleApiHelper$1.call(SourceFile:80)
08-29 18:16:19.783 15119 16402 E GoogleApiHelper: 	at com.life360.android.core.network.GoogleApiHelper$1.call(SourceFile:74)
08-29 18:16:19.783 15119 16402 E GoogleApiHelper: 	at io.reactivex.internal.operators.observable.ak.subscribeActual(SourceFile:42)
08-29 18:16:19.783 15119 16402 E GoogleApiHelper: 	at io.reactivex.s.subscribe(SourceFile:11194)
08-29 18:16:19.783 15119 16402 E GoogleApiHelper: 	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$a.run(SourceFile:96)
08-29 18:16:19.783 15119 16402 E GoogleApiHelper: 	at io.reactivex.aa$a.run(SourceFile:463)
08-29 18:16:19.783 15119 16402 E GoogleApiHelper: 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(SourceFile:66)
08-29 18:16:19.783 15119 16402 E GoogleApiHelper: 	at io.reactivex.internal.schedulers.ScheduledRunnable.call(SourceFile:57)
08-29 18:16:19.783 15119 16402 E GoogleApiHelper: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-29 18:16:19.783 15119 16402 E GoogleApiHelper: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
08-29 18:16:19.783 15119 16402 E GoogleApiHelper: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-29 18:16:19.783 15119 16402 E GoogleApiHelper: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-29 18:16:19.783 15119 16402 E GoogleApiHelper: 	at java.lang.Thread.run(Thread.java:764)
08-29 18:16:19.789 15119 16401 E GoogleApiHelper: unable to connect to reverse geocode service 
08-29 18:16:19.789 15119 16401 E GoogleApiHelper: java.io.IOException: Service not Available
08-29 18:16:19.789 15119 16401 E GoogleApiHelper: 	at android.location.Geocoder.getFromLocation(Geocoder.java:136)
08-29 18:16:19.789 15119 16401 E GoogleApiHelper: 	at com.life360.android.core.network.GoogleApiHelper$1.call(SourceFile:80)
08-29 18:16:19.789 15119 16401 E GoogleApiHelper: 	at com.life360.android.core.network.GoogleApiHelper$1.call(SourceFile:74)
08-29 18:16:19.789 15119 16401 E GoogleApiHelper: 	at io.reactivex.internal.operators.observable.ak.subscribeActual(SourceFile:42)
08-29 18:16:19.789 15119 16401 E GoogleApiHelper: 	at io.reactivex.s.subscribe(SourceFile:11194)
08-29 18:16:19.789 15119 16401 E GoogleApiHelper: 	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$a.run(SourceFile:96)
08-29 18:16:19.789 15119 16401 E GoogleApiHelper: 	at io.reactivex.aa$a.run(SourceFile:463)
08-29 18:16:19.789 15119 16401 E GoogleApiHelper: 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(SourceFile:66)
08-29 18:16:19.789 15119 16401 E GoogleApiHelper: 	at io.reactivex.internal.schedulers.ScheduledRunnable.call(SourceFile:57)
08-29 18:16:19.789 15119 16401 E GoogleApiHelper: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-29 18:16:19.789 15119 16401 E GoogleApiHelper: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
08-29 18:16:19.789 15119 16401 E GoogleApiHelper: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-29 18:16:19.789 15119 16401 E GoogleApiHelper: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-29 18:16:19.789 15119 16401 E GoogleApiHelper: 	at java.lang.Thread.run(Thread.java:764)
08-29 18:16:20.316  2243  2243 I PhenotypeExpConfig: refreshConfiguration() : Force = false : UpdateAvailable = false : Age = 30 minutes : MaxAge = 720 minutes
08-29 18:16:20.316  2243  2243 E RecyclerView: Cannot scroll to position a LayoutManager set. Call setLayoutManager with a non-null argument.
08-29 18:16:20.317  2243  2243 I AndroidIME: LatinIme.onDeactivate()
08-29 18:16:20.321 15119 15119 I Google Maps Android API: Google Play services package version: 18385019
08-29 18:16:20.349  2243  2243 I GoogleInputMethod: onTrimMemory(): 20
08-29 18:16:20.674  2715 16763 E NLP     : Exception
08-29 18:16:20.674  2715 16763 E NLP     : java.lang.SecurityException: need INSTALL_LOCATION_PROVIDER permission, or UID of a currently bound location provider
08-29 18:16:20.674  2715 16763 E NLP     : 	at android.os.Parcel.createException(Parcel.java:1950)
08-29 18:16:20.674  2715 16763 E NLP     : 	at android.os.Parcel.readException(Parcel.java:1918)
08-29 18:16:20.674  2715 16763 E NLP     : 	at android.os.Parcel.readException(Parcel.java:1868)
08-29 18:16:20.674  2715 16763 E NLP     : 	at android.location.ILocationManager$Stub$Proxy.reportLocation(ILocationManager.java:1646)
08-29 18:16:20.674  2715 16763 E NLP     : 	at com.android.location.provider.LocationProviderBase.reportLocation(LocationProviderBase.java:137)
08-29 18:16:20.674  2715 16763 E NLP     : 	at com.google.android.location.network.NetworkLocationChimeraService.a(:com.google.android.gms@18385019@18.3.85 (040400-262677519):6)
08-29 18:16:20.674  2715 16763 E NLP     : 	at sub.handleMessage(Unknown Source:6)
08-29 18:16:20.674  2715 16763 E NLP     : 	at suf.run(:com.google.android.gms@18385019@18.3.85 (040400-262677519):8)
08-29 18:16:20.674  2715 16763 E NLP     : 	at sus.b(:com.google.android.gms@18385019@18.3.85 (040400-262677519):33)
08-29 18:16:20.674  2715 16763 E NLP     : 	at sus.run(:com.google.android.gms@18385019@18.3.85 (040400-262677519):21)
08-29 18:16:20.674  2715 16763 E NLP     : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-29 18:16:20.674  2715 16763 E NLP     : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-29 18:16:20.674  2715 16763 E NLP     : 	at tax.run(Unknown Source:7)
08-29 18:16:20.674  2715 16763 E NLP     : 	at java.lang.Thread.run(Thread.java:764)
08-29 18:16:20.674  2715 16763 E NLP     : Caused by: android.os.RemoteException: Remote stack trace:
08-29 18:16:20.674  2715 16763 E NLP     : 	at com.android.server.LocationManagerService.checkCallerIsProvider(LocationManagerService.java:2811)
08-29 18:16:20.674  2715 16763 E NLP     : 	at com.android.server.LocationManagerService.reportLocation(LocationManagerService.java:2836)
08-29 18:16:20.674  2715 16763 E NLP     : 	at android.location.ILocationManager$Stub.onTransact(ILocationManager.java:681)
08-29 18:16:20.674  2715 16763 E NLP     : 	at android.os.Binder.execTransact(Binder.java:731)
08-29 18:16:20.674  2715 16763 E NLP     :

**Comment by steadfasterX** [comment]
whats the issue? google maps is not working?

**Comment by pavlaras** [comment]
> whats the issue? google maps is not working?

google maps is working perfectly. 
users say that 3rd party apps can't show "google maps".
For example app "life360"
Another app was reported here : https://forum.xda-developers.com/showpost.php?p=80020851&postcount=5560
"Runtastic Road Bike".
It seems that where it was supposed to show google maps, it doesn't

**Comment by steadfasterX** [comment]
related to IZat qualcomm location service?!

[logcat](https://github.com/Suicide-Squirrel/issues_pie/files/3633275/Text-1.txt)

might be related:
https://github.com/LineageOS/android_device_samsung_jf-common/commit/6e237262451a1748283b0eafdfac5f83d885cb9d

we miss "libprocessgroup" :
https://android.googlesource.com/platform/hardware/qcom/gps/+/92748935c6ecbc2f0cbb4447dc26034eefcb4dac%5E%21/#F1

**Comment by TermeHansen** [comment]
Life360 working fine here on latest build (160919) of LOS on H815

**Comment by steadfasterX** [comment]
> related to IZat qualcomm location service?!
> 
> [logcat](https://github.com/Suicide-Squirrel/issues_pie/files/3633275/Text-1.txt)
> 
> might be related:
> [LineageOS/android_device_samsung_jf-common@6e23726](https://github.com/LineageOS/android_device_samsung_jf-common/commit/6e237262451a1748283b0eafdfac5f83d885cb9d)
> 
> we miss "libprocessgroup" :
> https://android.googlesource.com/platform/hardware/qcom/gps/+/92748935c6ecbc2f0cbb4447dc26034eefcb4dac%5E%21/#F1

definitively NOT related to iZat. 
other then that, the following has been tested on latest LOS 16 without issues:

* the old one here: https://apkpure.com/runtastic-road-bike-trails-gps-bike-tracker/com.runtastic.android.roadbike.lite and the new one here: https://play.google.com/store/apps/details?id=com.runtastic.android
* waze (having its own map though so not related to gmaps but I read someone mentioned that as well)
* life360
