### ISSUE TITLE
DT2W not working

### ISSUE THREAD

**Issue by gioyann** [Suicide-Squirrel/issues_pie#34]
I make a massive use of Double Touch to Wake technology, I find it very useful expecially when my phone is plugged in my car. 

In this release it doesn't even appear a possibility to set it, issue which will lead me to come back to a previous LOS. Is there any possibility to fix it?

**Comment by steadfasterX** [comment]
Try 3rd party apps.
it has been completely removed as it had many issues and a lot of battery drain when it goes wild.
a little hope: aoelary doing AEX MIGHT add a different approach to get that work again.
