### ISSUE TITLE
[Request] add usb menu shortcut in notification menu

### ISSUE THREAD

**Issue by ANDROID2468** [Suicide-Squirrel/issues_pie#42]
You can do this by putting this in the system.prop...
`# Switching Menu of Mass storage and MTP`
`ro.sys.usb.storage.type=mtp,mass_storage`

what this looks like...
![usb](https://user-images.githubusercontent.com/39718118/72776437-d83b6500-3bd7-11ea-965f-3a6837f06291.png)

**Comment by steadfasterX** [comment]
Hm I have this here without any changes.
What does it look like when you do not set the property?

**Comment by ANDROID2468** [comment]
@steadfasterX  wow, I must be blind! I swear that it wasn't there before.  : /
