### ISSUE TITLE
4G and sms work, calls don't. - H815

### ISSUE THREAD

**Issue by LifelessMuffin** [Suicide-Squirrel/issues_pie#45]
Hello everyone, basically I have found out that with my h815 running LOS Oreo or Pie (even after a fresh install) it is not able to do or get calls, while LTE (so mobile internet) works and I can also get and send sms. I suspect that my device is faulty because there are some other weird things happening that in other same model devices don't happen. Actually I switched back to the stock 29a where everything seems to work fine.
 Here a screenshot which might explain the reason:

_<ADMIN NOTE: REMOVED PIC FOR SECURITY REASON (IMEI)>_

**Comment by steadfasterX** [comment]
1. UsU or officially unlocked?
1. ensure you use h815 20p bootloader and modem (the following is for not UsU'd devices only: [h815_20p_bootloader_20p_modem_TWRP-flashable.zip])(http://leech.binbash.rocks:8008/stock/LG/h815/20p/)
1. flash the [boot and system partition of 20p](http://leech.binbash.rocks:8008/stock/LG/h815/20p/extracted/) as well and boot it. Does the issue happens here as well?
1. flash LOS 16, is the issue gone now?
1. if not: provide logs when trying to do a call (https://bit.do/logcat - SEPCIFIC issue)

**Comment by serenita** [comment]
Hi,
I'm on an LG G4 international (h815) with /e/OS 0.18-20210815130098 (the OFFICIAL build) installed. The issue also appeared on the earlier /e/OS 0.17 and on the CUSTOM build. The bootloader is unlocked the official way.

I cannot make calls nor receive them. Mobile data works fine and SMS too. If someone called, though, I can see afterwards that I have a missed call. But I don't see the incoming call when it is actually made. If I try to call a number, it doesn't do the ringing sound on my phone but it just says it would call. Then, after some seconds, it just ends the call without any error message. Maybe it's worth mentioning that the problem did not arise directly after an update or flash. Rather, first, receiving calls stopped working, then calling. So it might well be a hardware-related issue but I wanted to report it anyway.

My SIM card works in other phones so it shouldn't be the problem. I also tried another dialer app but that doesn't change anything.

Here's a log of trying to call:
https://pastebin.com/kGUDvgAu

I would appreciate help!
Cheers
