### ISSUE TITLE
h815: SMS receiving broke (sending still works) when upgrading to 15.1/16.

### ISSUE THREAD

**Issue by eddyb** [Suicide-Squirrel/issues_pie#46]
You can see my previous report at https://github.com/Suicide-Squirrel/issues_oreo/issues/24.
I was slow to update but I'm on `lineage-16.0-20200324-UNOFFICIAL-h815` now and the exact same problem is there.

I've tested this again, and if someone sends me an SMS, I can move the SIM to my second phone and after a while (half an hour I think?), that second phone gets the unreceived SMS.

So I'm starting to suspect a baseband firmware ("modem?") bug, but I'm not sure if I can upgrade it in any way from `3-00101-M8992FAAAANAZM-1.31581.1`.

Is there any way to get logs from that part of the system? Maybe it explicitly reports an issue but then none of the Android UI knows about it or tries to display any message.

**Comment by eddyb** [comment]
Just to see what happens, I flashed `G4_29a_N_modem_UsU.zip` (from https://androidfilehost.com/?w=files&flid=239970), and nothing changed (I'm not even on UsU, my G4 is officially unlocked).

Well, the baseband version changed to `992FAAAANAZM-1.102416.2.104734.1`, but everything seems to work exactly the same.

I made a backup of the `modem` partition with `dd` before I did that though, so I can go back.

**Comment by steadfasterX** [comment]
> Just to see what happens, I flashed `G4_29a_N_modem_UsU.zip` (from https://androidfilehost.com/?w=files&flid=239970), and nothing changed (I'm not even on UsU, my G4 is officially unlocked).
> 
> Well, the baseband version changed to `992FAAAANAZM-1.102416.2.104734.1`, but everything seems to work exactly the same.
> 
> I made a backup of the `modem` partition with `dd` before I did that though, so I can go back.

wow you flashed an UsU file on your phone which is not UsU'd. next pls dont do stuff like that as that can easily BRICK YOUR PHONE! UsU and non-UsU files are WAY different and not the content in general but the bootloader parts within. you had luck this time.
other then that the only supported and 100% working bootloader firmware for the h815 is 20p! that one is linked in the LOS 16 thread as a TWRP flashable zip.

**Comment by eddyb** [comment]
I only changed the `modem` partition (and successfully changed it back to my backup, so now Baseband version says `3-00101-M8992FAAAANAZM-1.31581.1` again).
My understanding is that TWRP doesn't require the `modem` partition to be valid in order to work (or maybe it's just that the baseband firmware isn't loaded so which version/flavor it is doesn't matter).

<hr/>

Anyway, dangerous firmware experimentation aside, is there any log that could offer some insight into why receiving SMSes might fail?

I keep getting the test SMSes on the other phone I move the SIM to, within a few hours, which suggests to me that my mobile provider doesn't ever see an attempt to grab them at all, because they would presumably be lost if they were dropped somewhere e.g. in the Messages app itself.

**Comment by eddyb** [comment]
Installing the 20p modem didn't change the Baseband version reported by Android, nor fix the problem.

I ended up looking inside the partition and I've managed to track down which version my backup had.
The contents are the same as 20g from [this post](https://forum.xda-developers.com/g4/development/stock-h815-20g-images-kdz-flashable-t3450503).

So effectively I've now upgraded my modem from 20g to 20p.

However, I've not replaced anything other than the modem, at any point since installing LineageOS 14.
IIRC I might've had to upgrade something (maybe bootloader included) in order to do that, but 15.1 and 16 required, at most, only TWRP updates.

**Comment by steadfasterX** [comment]
@eddyb 
did you read and followed the last sentence here ? https://github.com/Suicide-Squirrel/issues_pie/issues/46#issuecomment-612783991 
.. it seems not

**Comment by eddyb** [comment]
Just tried non-UsU 29a modem (which is what is bundled with 20p in the LOS 16 post you mentioned. the modem version not being the same as the bootloader version is confusing) and "Baseband version" is now `992FAAAANAZM-1.102416.2.104734.1` (just like the UsU version).

<hr/>

But this isn't a firmware problem at all, I just didn't know about `adb logcat -b radio`.
So the real problem is an NPE in Java which is reported as a NAK to the SMSC, and *that's* why I get SMSes on the second phone later.
```
04-14 13:01:31.872  3663  3725 D RILJ    : [UNSL]< UNSOL_RESPONSE_NEW_SMS [SUB0]
04-14 13:01:31.946  3663  3736 D GsmInboundSmsHandler: IdleState.processMessage:1
04-14 13:01:31.946  3663  3736 D GsmInboundSmsHandler: Idle state processing message type 1
04-14 13:01:31.949  3663  3736 D GsmInboundSmsHandler: acquired wakelock, leaving Idle state
04-14 13:01:31.949  3663  3736 D GsmInboundSmsHandler: entering Delivering state
04-14 13:01:31.949  3663  3736 D GsmInboundSmsHandler: DeliveringState.processMessage:1
04-14 13:01:31.958  3663  3736 D TelephonyComponentFactory: makeInboundSmsTracker
04-14 13:01:31.999  3663  3736 E GsmInboundSmsHandler: Exception dispatching message
04-14 13:01:31.999  3663  3736 E GsmInboundSmsHandler: java.lang.NullPointerException: Uri must not be null
04-14 13:01:31.999  3663  3736 E GsmInboundSmsHandler:  at android.os.Parcel.createException(Parcel.java:1956)
04-14 13:01:31.999  3663  3736 E GsmInboundSmsHandler:  at android.os.Parcel.readException(Parcel.java:1918)
04-14 13:01:31.999  3663  3736 E GsmInboundSmsHandler:  at android.os.Parcel.readException(Parcel.java:1868)
04-14 13:01:31.999  3663  3736 E GsmInboundSmsHandler:  at android.content.IContentService$Stub$Proxy.notifyChange(IContentService.java:812)
04-14 13:01:31.999  3663  3736 E GsmInboundSmsHandler:  at android.content.ContentResolver.notifyChange(ContentResolver.java:2097)
04-14 13:01:31.999  3663  3736 E GsmInboundSmsHandler:  at com.android.providers.telephony.SmsProvider.notifyChange(SmsProvider.java:841)
04-14 13:01:31.999  3663  3736 E GsmInboundSmsHandler:  at com.android.providers.telephony.SmsProvider.insert(SmsProvider.java:453)
04-14 13:01:31.999  3663  3736 E GsmInboundSmsHandler:  at android.content.ContentProvider$Transport.insert(ContentProvider.java:267)
04-14 13:01:31.999  3663  3736 E GsmInboundSmsHandler:  at android.content.ContentResolver.insert(ContentResolver.java:1588)
04-14 13:01:31.999  3663  3736 E GsmInboundSmsHandler:  at com.android.internal.telephony.InboundSmsHandler.addTrackerToRawTable(InboundSmsHandler.java:1264)
04-14 13:01:31.999  3663  3736 E GsmInboundSmsHandler:  at com.android.internal.telephony.InboundSmsHandler.addTrackerToRawTableAndSendMessage(InboundSmsHandler.java:735)
04-14 13:01:31.999  3663  3736 E GsmInboundSmsHandler:  at com.android.internal.telephony.InboundSmsHandler.dispatchNormalMessage(InboundSmsHandler.java:723)
04-14 13:01:31.999  3663  3736 E GsmInboundSmsHandler:  at com.android.internal.telephony.gsm.GsmInboundSmsHandler.dispatchMessageRadioSpecific(GsmInboundSmsHandler.java:143)
04-14 13:01:31.999  3663  3736 E GsmInboundSmsHandler:  at com.android.internal.telephony.InboundSmsHandler.dispatchMessage(InboundSmsHandler.java:618)
04-14 13:01:31.999  3663  3736 E GsmInboundSmsHandler:  at com.android.internal.telephony.InboundSmsHandler.handleNewSms(InboundSmsHandler.java:544)
04-14 13:01:31.999  3663  3736 E GsmInboundSmsHandler:  at com.android.internal.telephony.InboundSmsHandler.access$900(InboundSmsHandler.java:97)
04-14 13:01:31.999  3663  3736 E GsmInboundSmsHandler:  at com.android.internal.telephony.InboundSmsHandler$DeliveringState.processMessage(InboundSmsHandler.java:438)
04-14 13:01:31.999  3663  3736 E GsmInboundSmsHandler:  at com.android.internal.util.StateMachine$SmHandler.processMsg(StateMachine.java:992)
04-14 13:01:31.999  3663  3736 E GsmInboundSmsHandler:  at com.android.internal.util.StateMachine$SmHandler.handleMessage(StateMachine.java:809)
04-14 13:01:31.999  3663  3736 E GsmInboundSmsHandler:  at android.os.Handler.dispatchMessage(Handler.java:106)
04-14 13:01:31.999  3663  3736 E GsmInboundSmsHandler:  at android.os.Looper.loop(Looper.java:193)
04-14 13:01:31.999  3663  3736 E GsmInboundSmsHandler:  at android.os.HandlerThread.run(HandlerThread.java:65)
04-14 13:01:31.999  3663  3736 E GsmInboundSmsHandler: Caused by: android.os.RemoteException: Remote stack trace:
04-14 13:01:31.999  3663  3736 E GsmInboundSmsHandler:  at com.android.server.content.ContentService.notifyChange(ContentService.java:393)
04-14 13:01:31.999  3663  3736 E GsmInboundSmsHandler:  at android.content.IContentService$Stub.onTransact(IContentService.java:100)
04-14 13:01:31.999  3663  3736 E GsmInboundSmsHandler:  at com.android.server.content.ContentService.onTransact(ContentService.java:262)
04-14 13:01:31.999  3663  3736 E GsmInboundSmsHandler:  at android.os.Binder.execTransact(Binder.java:731)
04-14 13:01:31.999  3663  3736 E GsmInboundSmsHandler: 
04-14 13:01:32.003  3663  3736 D RILJ    : [4156]> SMS_ACKNOWLEDGE success = false cause = 255 [SUB0]
```

**Comment by eddyb** [comment]
Renamed this file and now SMS receiving works:
`/data/user_de/0/com.android.providers.telephony/databases/mmssms.db`

Somehow nobody else on the internet ever had this problem, argh.

Should've just tried to debug it myself last year, reading the implementation and figuring out the database might be incomplatible took me only an hour.

**Comment by steadfasterX** [comment]
wow thanks for your detailed report (and fix) on this!
but anyways the 20p bootloader is the way to go not an unofficial BETA release .. but up to you ofc.

**Comment by eddyb** [comment]
>  but anyways the 20p bootloader is the way to go not an unofficial BETA release .. but up to you ofc.

I mean, I haven't touched the bootloader in a long while, and AFAIK it's the only part of the firmware capable of permanently bricking my phone. But I guess LGUP might be able to get around that?

<hr/>

So looking closer at the database (mostly because I didn't want to lost my SMS history), it seemed that [the most recent database upgrade](https://android.googlesource.com/platform/packages/providers/TelephonyProvider/+/android-9.0.0_r55/src/com/android/providers/telephony/MmsSmsDatabaseHelper.java#1817) didn't trigger (or failed for whatever reason). So I did:
```sql
sqlite> .schema raw
CREATE TABLE raw (_id INTEGER PRIMARY KEY,date INTEGER,reference_number INTEGER,count INTEGER,sequence INTEGER,destination_port INTEGER,address TEXT,sub_id INTEGER DEFAULT -1, pdu TEXT,deleted INTEGER DEFAULT 0,message_body TEXT);
sqlite> ALTER TABLE raw ADD COLUMN display_originating_addr TEXT;
sqlite> .schema raw
CREATE TABLE raw (_id INTEGER PRIMARY KEY,date INTEGER,reference_number INTEGER,count INTEGER,sequence INTEGER,destination_port INTEGER,address TEXT,sub_id INTEGER DEFAULT -1, pdu TEXT,deleted INTEGER DEFAULT 0,message_body TEXT, display_originating_addr TEXT);
```

Because I opened the Messages app with the database moved away, I had to delete the Messages app's data, in order for it to load again the entire history from the now-fixed `mmssms.db`.

Receiving SMSes works now *and* I kept my entire message history (worst case I would've used an SMS backup/restore app or just keep the database and poke at it if I ever need something from it).

**Comment by steadfasterX** [comment]
> So looking closer at the database (mostly because I didn't want to lost my SMS history), it seemed that [the most recent database upgrade](https://android.googlesource.com/platform/packages/providers/TelephonyProvider/+/android-9.0.0_r55/src/com/android/providers/telephony/MmsSmsDatabaseHelper.java#1817) didn't trigger (or failed for whatever reason). 

nice catch again ;)
most likely reason for that update failure could be a selinux denial..
