### ISSUE TITLE
h815: "Advanced Restart" developer option doesn't seem to have an effect.

### ISSUE THREAD

**Issue by eddyb** [Suicide-Squirrel/issues_pie#47]
In the past I had enabled "Advanced Restart" so that I can easily reboot into recovery (starting the phone with <kbd>Power</kbd>+<kbd>Volume Down</kbd> works but the "wipe" that starts TWRP is a bit unnerving every time).

But since I've upgraded to `lineage-16.0-20200324-UNOFFICIAL-h815`, that option doesn't seem to do anything, and I wonder if anyone else noticed something similar.

**Comment by steadfasterX** [comment]
works 100%. I saw an issue like that before when not clean flashed though.

**Comment by eddyb** [comment]
Thanks, that's what I wanted to check.

I don't have the time to go through all the steps for a clean flash right now (among other things, I have a bank token app I'd have to re-activate). It was a nightmare to sift through everything in the data partition backup from the original LG install (that broke and forced me to move to LineageOS).

Besides individual apps crashing, the biggest issue was that unlocking crashed SystemUI (so I couldn't get into the system after the upgrade), which I fixed by renaming [relevant files](https://www.reddit.com/r/LineageOS/comments/eyuzs1/lineageos_16_gui_crashes_after_unlock/fgjg3qt/) in TWRP.

I mostly upgraded to try and see if #46 is still a problem.

Anyway, I'll close this and leave another comment if I figure out what to poke at to unbreak it.

**Comment by steadfasterX** [comment]
yes restoring apps including data and settings causing issues always when coming from another ROM and even sometimes when coming from the same custom ROM when moving to a higher major version (i.e. 15.1->16 etc).

**Comment by eddyb** [comment]
Oddly enough, after doing https://github.com/Suicide-Squirrel/issues_pie/issues/46#issuecomment-613385252 (or something I did before, although I don't remember doing anything), this problem resolved itself.
