### ISSUE TITLE
Signature Spoofing Is broken 

### ISSUE THREAD

**Issue by ANDROID2468** [Suicide-Squirrel/issues_pie#50]
...
![Screenshot_20200617-235100_Package_installer](https://user-images.githubusercontent.com/39718118/84980898-e515a380-b0f8-11ea-8274-25437f3e66bf.png)
![Screenshot_20200617-235110_Signature_Spoofing_Checker](https://user-images.githubusercontent.com/39718118/84980900-e5ae3a00-b0f8-11ea-9e82-ac60bf8c12f7.png)

**Comment by steadfasterX** [comment]
Did you followed the FAQ 9?
https://forum.xda-developers.com/showpost.php?p=79502871&postcount=2
Especially step 3 a?

**Comment by ANDROID2468** [comment]
![man-facepalming_1f926-200d-2642-fe0f](https://user-images.githubusercontent.com/39718118/84984909-5f4a2600-b101-11ea-847b-df54bb0fd6fe.png)
wow I feel stupid now...
