### ISSUE TITLE
Double tap to wake

### ISSUE THREAD

**Issue by pavlaras** [Suicide-Squirrel/issues_pie#51]
It is an old issue, not a new.

i figured it out what's the problem with the wake up functions not working. but i need some help to tail the root of the problem.

https://github.com/Suicide-Squirrel/Titan-Kernel-LG-G4/blob/93930b9f3536cfc016b5b1dce8237e0e08dbc44c/drivers/input/touchscreen/lge_touch_core.c#L2804

show_lpwg_data watch the lpwg_data and creates a table with the values.

Then we send the table to store_lpwg_data, and so on. Not interested further.

lpwg_data in file tree is located here:
"/sys/devices/virtual/input/lge_touch/lpwg_data"

When this lpwg_data gets a value bigger than 0 (it takes coords of the taps), it sends the coords to the input0 device ("/dev/input0") which then triggers the node to send a wake up command.

So this is how the wake up event works

Now the problem:
I guess , the watcher for lpwg_data is not working properly and that's why it is late to send the lpwg_data to the node "show_lpwg_data".

I need to tail this in kernel.
Which function sends the "lpwg_data" to the sysfs node "show_lpwg_data"

if i find where the "lpwg_data" comes from originally in the kernel, then i can fix the wake up function once and for all.

**Comment by steadfasterX** [comment]
btw and as said already long time ago:

as we know double tap works in 3..4 of 10 times as it should.
but in 9 of 10 times it gets detected properly - just the display does not activate the communicated brightness level. that can be re-produced when looking at the display in a VERY dark room. you can see that it turned on just with a brightness of ... well 1 as it looks like. and yea the brightness level gets set properly to what it should (e.g. 160) but still the display just do not react on that. logcat while grep on brightness showing that clearly.

for re-producing you need to really wait until the display turns off from itself (so set lowest wait and direct sleep) and let it off for a while (iirc 5 min or even longer)

**Comment by adatum** [comment]
Confirming that I experience this issue of failure to wake from double tap on a LG G4 H812 on /e/ pie. Even in a dark room the screen looks completely off. EDIT: Now I also got the situation of the LCD turning on but not the backlight. So, with this issue, sometimes the screen doesn't turn on at all, and other times it turns on but the backlight is off (or extremely dim).

Also, even when double tap to wake works, it can take a delay of 1-2 seconds, which feels really long. I wonder if sometimes a delay can give the impression that double tap to wake did not work, prompting another double tap from the user which then legitimately turns the screen off...
