### ISSUE TITLE
Screen tearing issue in Pie based roms (general UI element bugs)

### ISSUE THREAD

**Issue by PastorCatto** [Suicide-Squirrel/issues_pie#54]
i have an LG G4 (H812 Canadian) and i have just been using H811 based roms as that is what SALT states my GPT layout is, and the only really big issue is lots of screen tearing, and ive attempted to force all ui components to be rendered through the GPU but with no positive affect. i can try to pull a logcat if need be, but i wouldnt know if that helps

**Comment by steadfasterX** [comment]
In your fav ROM do this:

`adb shell getprop debug.hwui.renderer`

If you get an empty result it means skiaGL is active. It has glitches but some find it faster then opengl.

If you wanna go back and enforce OpenGL you can do so by

**temporary (immediately active):**

```
adb root (must be enabled in dev options )
adb shell setprop debug.hwui.renderer opengl
```

**persistent:**

```
boot TWRP
backup system !!!!!!!
mount system
adb shell
echo "debug.hwui.renderer=opengl" >> /system/build.prop
sync
reboot
```
