### ISSUE TITLE
H815 - Enabling encryption causes reboot loop

### ISSUE THREAD

**Issue by fmikker** [Suicide-Squirrel/issues_pie#55]
After enabling encryption the device is stuck in a reboot loop.
The same issue that I was experiencing using the custom built LineageOS 16 which I reported on [earlier.](https://github.com/Suicide-Squirrel/issues_pie/issues/12). 
This time I have not installed Magisk or set a unlock password/pin/pattern prior to enabling encryption, just the stock OS and nothing else.

System information
Unlock: Official
OS: e-1.0-p-20200826-CUSTOM-h815.zip
Modem: h815_20p_bootloader_20p_modem_TWRP-flashable.zip
TWRP: me.twrp.twrpapp-26.apk

Steps to reproduce:
1. Wipe the device as described in the [installation instructions](https://forum.xda-developers.com/g4/development/rom-e-os-t4142021l)
2. Install the updated modem image
3. Install e-1.0-p-20200826-CUSTOM-h815.zip
4. Enable encryption

What I expected:
The encryption is enabled and the device is functioning with encryption

What happened instead:
The device is stuck in a reboot loop where the LG logo is displayed, and sometimes the e//-logo, and then the device reboots in 5-8 seconds.

**Comment by steadfasterX** [comment]
> TWRP: me.twrp.twrpapp-26.apk

So which TWRP version is that? this is not a real TWRP version number. Do you have installed the latest P - PREVIEW as suggested? This MIGHT be related to your issue!


> 1. Wipe the device as described in the [installation instructions](https://forum.xda-developers.com/g4/development/rom-e-os-t4142021l)

just to be clear: you did a FULL CLEAN wipe? so for sure FORMATed data?

> 2. Install the updated modem image

you said above that you have the modem and bootloader stack  h815_20p_bootloader_20p_modem_TWRP-flashable.zip  is that what you mean by "updated modem image" ? Actually it is the bootloader stack + modem but I wanna be sure what you flashed here.

share the logs! 
FAQ link: https://forum.xda-developers.com/showpost.php?p=83196387&postcount=2
steps:

1. **full clean** wipe as described in FAQ 2. Important: ensure you have the latest TWRP P preview and also ensure you do not miss the step "Factory Reset" as this ensures a clean state for the encrypt partition (see https://github.com/Suicide-Squirrel/issues_pie/issues/52)
1. do not flash anything else, no magisk no nothing.
1. let it boot
1. grab the logs as in FAQ  "#07b: How can I provide a clean boot log?" 
1. let it boot again
1. encrypt
1. when the boot loop occurs power off the device after it hangs there or when it reboots automatically just ensure you boot DIRECTLY to TWRP/SHRP instead.
1. grab the logs as in FAQ  "#07b: How can I provide a clean boot log?"
