### ISSUE TITLE
Build Fail

### ISSUE THREAD

**Issue by sdembis** [Suicide-Squirrel/issues_pie#57]
FAILED: /home/steve/Desktop/LOS_16.0_LG_G4_H812/out/target/product/h812_usu/obj/ETC/file_contexts.bin_intermediates/file_contexts.bin 
/bin/bash -c "(/home/steve/Desktop/LOS_16.0_LG_G4_H812/out/host/linux-x86/bin/checkfc /home/steve/Desktop/LOS_16.0_LG_G4_H812/out/target/product/h812_usu/obj/ETC/sepolicy_intermediates/sepolicy /home/steve/Desktop/LOS_16.0_LG_G4_H812/out/target/product/h812_usu/obj/ETC/file_contexts.bin_intermediates/file_contexts.concat.tmp ) && (/home/steve/Desktop/LOS_16.0_LG_G4_H812/out/host/linux-x86/bin/sefcontext_compile -o /home/steve/Desktop/LOS_16.0_LG_G4_H812/out/target/product/h812_usu/obj/ETC/file_contexts.bin_intermediates/file_contexts.bin /home/steve/Desktop/LOS_16.0_LG_G4_H812/out/target/product/h812_usu/obj/ETC/file_contexts.bin_intermediates/file_contexts.concat.tmp )"
/home/steve/Desktop/LOS_16.0_LG_G4_H812/out/target/product/h812_usu/obj/ETC/file_contexts.bin_intermediates/file_contexts.concat.tmp: Multiple same specifications for /data/misc/bluetooth(/.*)?.
/home/steve/Desktop/LOS_16.0_LG_G4_H812/out/target/product/h812_usu/obj/ETC/file_contexts.bin_intermediates/file_contexts.concat.tmp: Multiple same specifications for /data/misc/bluedroid(/.*)?.
Error: could not load context file from /home/steve/Desktop/LOS_16.0_LG_G4_H812/out/target/product/h812_usu/obj/ETC/file_contexts.bin_intermediates/file_contexts.concat.tmp
[ 81% 77761/95262] //bionic/libc:commo...ioner preprocess include [linux_glibc]
warning: attempted to generate guard with empty availability: obsoleted = 21
warning: attempted to generate guard with empty availability: obsoleted = 23
ninja: build stopped: subcommand failed.
15:44:03 ninja failed with: exit status 1

**Comment by steadfasterX** [comment]
Well .. that has been discussed a while ago in my (well known) TG group.. 

![Screenshot_20210509-192434](https://user-images.githubusercontent.com/8750713/117581368-af0c5400-b0fc-11eb-8305-e6ed18509bbb.jpg)

Mentioned commit: https://github.com/LGgFour/android_device_lge_g4-common/commit/19d4a4482a8a1f33d131b18f6dcaa55677273b3a

The link to my TG group can be found in my sig on xda but here again: https://t.me/sfX_Android
