### ISSUE TITLE
camera does not work

### ISSUE THREAD

**Issue by steadfasterX** [Suicide-Squirrel/issues_pie#6]
likely due to the wrong shiming here:
https://github.com/Suicide-Squirrel/android_device_lge_g4-common-LOS/commit/3b27b384b572f50a104d06d8d31172c392bbed15#diff-581794583e89a660d8f68651b78d17f9R45

## log

https://gist.github.com/steadfasterX/108c1c424f5a237d7e08afc6be34185b

**Comment by steadfasterX** [comment]
fixed by: 

https://github.com/Suicide-Squirrel/android_device_lge_g4-common-LOS/commit/6a95d4d57c39a96dafe47b2ccbe6e8fb5f859b51
https://github.com/Suicide-Squirrel/android_device_lge_g4-common-LOS/commit/00d7dad6f65525ebdfae7d7ff2dfd6e58366eaa5
https://github.com/Suicide-Squirrel/android_device_lge_g4-common-LOS/commit/a2c9f509d8a60465da8eabf64633c48089838aa0

**Comment by gioyann** [comment]
I had the same issue on LOS 15, I fixed by stopping native camera's app by "app manager" then installing Google camera. May it works for 16 too?

**Comment by steadfasterX** [comment]
> I had the same issue on LOS 15, I fixed by stopping native camera's app by "app manager" then installing Google camera. May it works for 16 too?

this issue is closed and fixed for pie
