### ISSUE TITLE
Adb not working 

### ISSUE THREAD

**Issue by LifelessMuffin** [Suicide-Squirrel/issues_pie#61]
Hi folks, I don't know if this is happening to anybody else as well, but when I try to run any adb command I get "no devices/emulators found" error. It is strange because when disabling adb from the Android's developer settings and revoking every access, then a new connection between the adb server and the device happens, asking me to approve the communication via that pop up window. After that no adb command work anymore, resulting in that error. 

Both my two h815 devices got this issue and both are running Pie (the first one runs the build form 8 June, while the second runs the last build from December). So I thought it could have been a problem with my usb port or cable, but by connecting my old chinese tablet running Android 5.1 adb shell/pull/push work just fine, so I exclude that.

I run adb on Ubuntu 20.04 and my machine is updated, I tried to remove adb completely and reinstalling it again but still it won't work. 

Thank you in advance as always :)

**Comment by rundumdieuhr** [comment]
What does 'adb devices' yield after you approved the new connection with the peer address?
Have you installed some level of extra security on the mobile that might intercept adb communication?

**Comment by LifelessMuffin** [comment]
> What does 'adb devices' yield after you approved the new connection with the peer address? Have you installed some level of extra security on the mobile that might intercept adb communication?

Hi, no I don't have any extra layer of security, maybe the only one could be "usb restrictions" under Trust. But it's weird, now it seems kinda working. Maybe earlier I accidentally plug it into the usb 3 port in the back of the desktop computer rather than an usb 2, but still can't explain why with the tablet it was totally fine

![2022-01-14 19-49-43](https://user-images.githubusercontent.com/58374136/149569724-ade8631d-7ffb-4072-a98a-8a9f0a3f3ab6.png)

**Comment by LifelessMuffin** [comment]
Now I'm trying to make a backup but it keeps stopping 
![2022-01-14 19-59-56](https://user-images.githubusercontent.com/58374136/149570852-ab428a9e-d57a-4620-8ca5-2ffed3e01e71.png)

![2022-01-14 20-07-38](https://user-images.githubusercontent.com/58374136/149571533-7ae7e740-3f71-4e44-8a80-45877ffb1492.png)

**Comment by rundumdieuhr** [comment]
Trust your USB cable? Tried another one?

**Comment by LifelessMuffin** [comment]
> Trust your USB cable? Tried another one?

So yes, I was able to buy a new one and apparently it is the cable. 
Thank you so much, sorry for making noise for nothing :)
