### ISSUE TITLE
WiFi hotspot does not work

### ISSUE THREAD

**Issue by steadfasterX** [Suicide-Squirrel/issues_pie#7]

**Comment by steadfasterX** [comment]
fixed by:

https://github.com/Suicide-Squirrel/proprietary_vendor_lge/commit/f2f3f5656445f8450810c4b72074838ab4f5685e
https://github.com/Suicide-Squirrel/proprietary_vendor_lge/commit/90b0f3fd06b7f7c26de1a98554ee9c9b37811353
https://github.com/Suicide-Squirrel/android_device_lge_g4-common-LOS/commit/4b95874d5db125bd76e3c52b4be9cbc96f37d1e8
https://github.com/Suicide-Squirrel/android_device_lge_g4-common-LOS/commit/9989b2c13b0b3165ebcbe1c407699548c614fc02
https://github.com/Suicide-Squirrel/android_device_lge_g4-common-LOS/commit/5a6a0fa97bf8fc645233f7b4cdeb985cd5f9a9dc
https://github.com/Suicide-Squirrel/android_device_lge_g4-common-LOS/commit/683fc60
https://github.com/Suicide-Squirrel/android_device_lge_g4-common-LOS/commit/05672ff

.... and maybe others :p

**Comment by steadfasterX** [comment]
hotspot works but sometimes when disabling it again => kernel crash (invalid RAM console)!

![be569faa-6f6d-4c98-af6c-ad4b15904258](https://user-images.githubusercontent.com/8750713/57055942-3073b500-6c9f-11e9-90f8-aa971f64f77a.jpeg)

**Comment by steadfasterX** [comment]
this bug does not affect a non-UsU device and maybe even not a regular UsU'd device as mine has more fuses blown then a regular one (see https://github.com/Suicide-Squirrel/issues_oreo/issues/11 for details)

This will be closed for now as I do not think it will affect "normal" devices.

**Comment by steadfasterX** [comment]
re-producible even on non-UsU devices

~needs further investigation as it can really be only UsU related.~
~Currently I test UsU builds on even a non-UsU device which would explain why it has the crash on non-UsU as well.~

~TODO: build pure h815 (bootimage at least) and test that on the non-UsU~

reports exist which clearly states that this is a general issue for any ROM and any device

**Comment by JMLS15** [comment]
Same problem with usb tethering = kernel crash

Sent from my LG G4 VS986 with the lastest lineage os 9.0 build.

**Comment by steadfasterX** [comment]
reportedly fixed by adding (thx for that awesome bring-up @WiZaRd981  )

https://github.com/rk779/android_kernel_leeco_msm8976/commit/3093bd6442b99277e5535b386bfc1a7453d03dfb

Change will be added for testing in one of the next builds (I haven't tested personally yet)

**Comment by steadfasterX** [comment]
fix has been tested on lineage-16.0-20190620-UNOFFICIAL-h815.zip successfully
