### ISSUE TITLE
Torch tile does not work

### ISSUE THREAD

**Issue by steadfasterX** [Suicide-Squirrel/issues_pie#8]
same as in oreo:
https://github.com/Suicide-Squirrel/issues_oreo/issues/14

### log

https://gist.github.com/steadfasterX/1320ee45629eb1531a27a2fa4639204f

**Comment by busattovini** [comment]
It looks like this bug can't be fixed! lol :)

**Comment by steadfasterX** [comment]
I am just tracking every issue I encounter so I can look later on those when I have the time so I do not forget.

**Comment by busattovini** [comment]
You're the greatest.

**Comment by steadfasterX** [comment]
fixed when being rooted (working on a fix which does not req root though)

**Comment by steadfasterX** [comment]
finally fixed (still a workaround though) by: https://github.com/Suicide-Squirrel/android_device_lge_g4-common/commit/7d1652a0461d9d17d58d7979c1135aece84d9651

This solution will work without root, is auto-added to the Quicksettings tile, is working properly even when selinux is enforcing... and so.. I will close that for now. Maybe some day someone find a real fix for that.
